docs: draft for sparse merkle trees
tari-project/rfcs pull request #105
Opened 2023-08-01 16:24 UTC by CjS77

2023-09-12 16:07 UTC, CjS77 commented
ACK

2023-09-13 13:43 UTC, SWvheerden reviewed
ACK

2023-09-13 17:19 UTC, AaronFeickert requested changes

2023-09-13 17:19 UTC, AaronFeickert commented on src/RFC-0141_Sparse_Merkle_Trees.md
> +fourth bit. This results in a SMT that looks like this:
The first and second indexes differ at the fourth bit, whereas the first and last pairs differ at the first bit.

2023-09-13 17:19 UTC, AaronFeickert commented on src/RFC-0141_Sparse_Merkle_Trees.md
> +  prefixes are not unique. For example, every key prefix for the left-mode path down the tree will always have a
Do you mean "left-most" here?

2023-09-13 17:19 UTC, AaronFeickert commented on src/RFC-0141_Sparse_Merkle_Trees.md
> +If the UTXO merkle root is replaced by a sparse merkle tree, this change would require a **hard fork**,
```suggestion
If the UTXO Merkle root is replaced by a sparse Merkle tree, this change would require a **hard fork**, 
```

2023-09-13 17:19 UTC, AaronFeickert commented on src/RFC-0141_Sparse_Merkle_Trees.md
> +since it fundamentally alters how the UTXO merkle root is calculated.
```suggestion
since it fundamentally alters how the UTXO Merkle root is calculated. 
```

2023-09-14 04:14 UTC, CjS77 commented on src/RFC-0141_Sparse_Merkle_Trees.md
> +fourth bit. This results in a SMT that looks like this:
```suggestion
you will notice that the first two diverge at the fourth bit, while the first and last pairs differ at the
first bit. This results in a SMT that looks like this:
```

2023-09-14 04:14 UTC, CjS77 commented on src/RFC-0141_Sparse_Merkle_Trees.md
> +     ┌┴┐                ┌┴┐1
```suggestion
     ┌┴┐0               ┌┴┐1
```

2023-09-14 04:14 UTC, CjS77 commented on src/RFC-0141_Sparse_Merkle_Trees.md
> + ┌┴┐     ┌┴┐        ┌┴┐10    ┌┴┐11
```suggestion
 ┌┴┐00   ┌┴┐01      ┌┴┐10    ┌┴┐11
```

2023-09-14 04:14 UTC, CjS77 commented on src/RFC-0141_Sparse_Merkle_Trees.md
> +     ┌┴┐     ┌┴┐       110┌┴┐   ┌┴┐111
```suggestion
     ┌┴┐010  ┌┴┐011     110┌┴┐   ┌┴┐111
```

2023-09-14 04:14 UTC, CjS77 commented on src/RFC-0141_Sparse_Merkle_Trees.md
> +  prefixes are not unique. For example, every key prefix for the left-mode path down the tree will always have a
```suggestion
  prefixes are not unique. For example, every key prefix for the left-most path down the tree will always have a 
```

2023-09-14 16:20 UTC, AaronFeickert approved these changes

2023-11-08 11:41 UTC, merged